### ISSUE TITLE
Reload串口占用问题

### ISSUE THREAD

**Issue by Hugh-rymcu** [rymcu/nebula-helper#1]
在软件打开串口的情况下，点击view菜单下的“Reload”或“Force Reload”后。再次打开该串口时显示打开失败。错误代码如下：
<img width="207" alt="串口打开失败" src="https://user-images.githubusercontent.com/57855411/88621561-60dd1580-d0d3-11ea-9c2c-2a995f0c8a35.png">

**Comment by ronger-x** [comment]
已禁用刷新界面,增加刷新串口列表功能(视图->刷新串口列表)
