### ISSUE TITLE
serialport 问题

### ISSUE THREAD

**Issue by beichenal** [rymcu/nebula-helper#10]
Uncaught TypeError: Cannot read property 'modules' of undefined
    at Object.eval (bindings.js?9fc5:29)
    at eval (bindings.js:223)
    at Object../node_modules/_bindings@1.5.0@bindings/bindings.js (chunk-vendors.js:208)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (linux.js?ee3b:2)
    at Object../node_modules/_@serialport_bindings@9.0.1@@serialport/bindings/lib/linux.js (chunk-vendors.js:65)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at Object.eval (index.js?9bac:14)

我的electron-vue 装了serialport 一require 就报上面的错误
下面是我的package.json 内容
{
  "name": "danlianjianche",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "core-js": "^3.6.5",
    "element-ui": "^2.4.5",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "electron": "^9.0.0",
    "electron-devtools-installer": "^3.1.0",
    "electron-rebuild": "^1.11.0",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "serialport": "^9.0.1",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.4",
    "vue-cli-plugin-element": "~1.0.1",
    "vue-template-compiler": "^2.6.11"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

系统win10 64 
请问哪里出了问题，该怎么解决呢

**Comment by ronger-x** [comment]
- serialport 是 nodejs 的 私有包需要重新编译成 electron 能用的,参见 https://github.com/serialport/node-serialport/issues/2089#issuecomment-665382212
- serialport 咱不能完美支持 electron@9.0.0 及以后的版本,参见 https://github.com/serialport/node-serialport/issues/2105

**Comment by Minori-ty** [comment]
同样的问题，请问你是怎么解决的？
