### ISSUE TITLE
联系

### ISSUE THREAD

**Issue by chen5805** [rymcu/nebula-helper#13]
你好，我目前也在做eletron+vue+serialPort的项目，我在本地运行没有问题，编译打包后找不到serialPort模块，我希望能够添加你的联系方式想你请教一些问题。微信：changhaipokong

**Comment by ronger-x** [comment]
你把你的项目放到 GitHub 上, 我可以帮你看看, 这样后来者也可以通过这个 issue 看到你碰到的问题及解决方法
