### ISSUE TITLE
serialport的问题一直解决不了

### ISSUE THREAD

**Issue by Minori-ty** [rymcu/nebula-helper#14]
加入serialport就一直报错，用了你的这个方法还是不行https://github.com/serialport/node-serialport/issues/2089#issuecomment-665382212
能帮我看一下吗？我的demo：https://github.com/Minori-ty/electron-error-demo

**Comment by ronger-x** [comment]
把你package.json 内的 install 替换成这个试试，不行的话周日晚上（在外身边没有电脑）我下载你的代码研究看看

"install": "npm rebuild --runtime=electron --target=8.4.0 --disturl=https://npm.taobao.org/mirrors/atom-shell --abi=76"

**Comment by Minori-ty** [comment]
> 把你package.json 内的 install 替换成这个试试，不行的话周日晚上（在外身边没有电脑）我下载你的代码研究看看
> 
> "install": "npm rebuild --runtime=electron --target=8.4.0 --disturl=https://npm.taobao.org/mirrors/atom-shell --abi=76"

我用你的办法，给vue添加一个全局属性，就报indexOf的错误。我不用，直接引用serialport的包，就报mudules的错误。
![image](https://user-images.githubusercontent.com/79521943/131081014-9d6066f1-ce88-4952-a54f-5d9c96ecfc49.png)

![image](https://user-images.githubusercontent.com/79521943/131080971-af07d2c3-cebc-42fe-81e7-18379013a0a5.png)

**Comment by Minori-ty** [comment]
> 把你package.json 内的 install 替换成这个试试，不行的话周日晚上（在外身边没有电脑）我下载你的代码研究看看
> 
> "install": "npm rebuild --runtime=electron --target=8.4.0 --disturl=https://npm.taobao.org/mirrors/atom-shell --abi=76"

这个install的效果是什么？替换下载的源吗？我用的是nrm，替换淘宝源

**Comment by ronger-x** [comment]
因为项目里用到了 NodeJS 的私有模块，你可以了解下 electron-builder 这里就是替代它的作用

—runtime：使用 electron 的 runtime 进行编译
-—target：选择你安装的 electron 版本
--disturl：electron下载地址，由于网络原因，可以切换成 npm 淘宝源
—abi：选择 Node 的 Module 版本，目前还没遇到需要修改的情况

**Comment by ronger-x** [comment]
讲错了，替代 node-gyp

**Comment by Minori-ty** [comment]
> 讲错了，替代 node-gyp

好的，等你的消息，感谢大佬

**Comment by Minori-ty** [comment]
> 讲错了，替代 node-gyp

我有几个问题想要请教一下，node版本是要32位还是要64位？python是要2.7还是3.6？serialport和electron的版本选择什么比较合适？编译的时候是用electron-rebuild吗？
