### ISSUE TITLE
十六进制显示功能

### ISSUE THREAD

**Issue by Hugh-rymcu** [rymcu/nebula-helper#3]
1.以一个字节为显示单位，每个字节之间需以一个空格隔开；
2.每个字节有两个字符组成，不足两个字符高位补0；
3.有效字符为0-9，A-F；
4.小写字母a-f,需强制转换为A-F。
<img width="80" alt="串口显示" src="https://user-images.githubusercontent.com/57855411/88622588-b3b7cc80-d0d5-11ea-8e9f-6fd4fa1c0fc1.png">

**Comment by ronger-x** [comment]
已修复
