### ISSUE TITLE
十六进制发送功能

### ISSUE THREAD

**Issue by Hugh-rymcu** [rymcu/nebula-helper#4]
1.十六进制，输入有效字符：0-9，a-f，A-F及空格；
2.输入非有效字符需提示字符非法；
3.输入字符串无空格的情况下，每2个字符组成一个字节，少于两个字符的高位补0；（字符串最后一个为空格，不算）
4.输入字符串有空格的情况下，空格前后必须是两个字符或一个字符，一个字符的高位补0。超过两个字符需提示字符串非法。

**Comment by ronger-x** [comment]
已修复
